# Generated by Django 3.1.4 on 2020-12-28 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("manufacturers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("model", models.CharField(max_length=255)),
                ("country_of_origin", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("state", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("size", models.CharField(max_length=255)),
                ("private", models.BooleanField(default=False)),
                ("buy_price", models.FloatField(blank=True, default=None, null=True)),
                ("can_be_sold", models.BooleanField(default=False)),
                ("private_note", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="categories.category"
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="manufacturers.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ("model",),
            },
        ),
    ]
