# Generated by Django 3.1.4 on 2020-12-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
