# Generated by Django 3.1.4 on 2020-12-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_auto_20201228_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="acquired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="country_of_origin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
