# Generated by Django 3.1.4 on 2020-12-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_auto_20201228_0708"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemweight",
            name="item",
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, related_name="item_weights", to="items.item"
            ),
            preserve_default=False,
        ),
    ]
