# Generated by Django 3.1.4 on 2020-12-28 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_auto_20201228_0718"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemWorks",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("summary", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("private", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="item_works", to="items.item"
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
    ]
