# Generated by Django 3.1.4 on 2020-12-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0008_auto_20201228_0736"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemWorks",
            new_name="ItemWork",
        ),
    ]
