# Generated by Django 3.1.4 on 2020-12-28 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0009_auto_20201228_0736"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemRelated",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="related_items", to="items.item"
                    ),
                ),
                ("related", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="items.item")),
            ],
        ),
    ]
