# Generated by Django 3.1.4 on 2020-12-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0010_itemrelated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrelated",
            name="related",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="related_items_item", to="items.item"
            ),
        ),
    ]
