# Generated by Django 3.1.4 on 2020-12-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0011_auto_20201228_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrelated",
            name="related",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_items_item",
                to="items.item",
                verbose_name="item",
            ),
        ),
        migrations.CreateModel(
            name="ItemLinks",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="item_links", to="items.item"
                    ),
                ),
            ],
        ),
    ]
