# Generated by Django 3.1.4 on 2020-12-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0014_auto_20201228_0805"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemFiles",
            new_name="ItemFile",
        ),
        migrations.RenameModel(
            old_name="ItemPictures",
            new_name="ItemPicture",
        ),
    ]
