# Generated by Django 3.1.4 on 2020-12-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0016_auto_20201228_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itempower",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="item_powers", to="items.item"
            ),
        ),
    ]
