# Generated by Django 3.1.4 on 2020-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0017_auto_20201228_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="buy_price",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
