# Generated by Django 3.1.4 on 2020-12-28 10:55

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_auto_20201228_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemwork',
            name='content_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, help_text='Markdown is supported.', rendered_field='description_rendered'),
        ),
        migrations.AlterField(
            model_name='item',
            name='plate_infos',
            field=markdownfield.models.MarkdownField(blank=True, help_text='Markdown is supported.', null=True, rendered_field='plate_infos_rendered'),
        ),
        migrations.AlterField(
            model_name='itemwork',
            name='content',
            field=markdownfield.models.MarkdownField(help_text='Markdown is supported.', rendered_field='content_rendered'),
        ),
    ]
