# Generated by Django 3.1.4 on 2020-12-30 10:35

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("items", "0023_auto_20201230_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="categories.category",
                verbose_name="Category",
            ),
        ),
    ]
