# Generated by Django 3.1.4 on 2021-01-02 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0025_auto_20201230_1150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemwork",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
